helicity=-pi/2;%helicity_y: 0 (right neel),pi (left neel), pi/2 (bloch CW),-pi/2 (bloch (CCW)
domain=482;
domainWall=60;

sim_size_x=32;
sim_size_y=512;
sim_height=100;

im_skel=zeros(sim_size_y,sim_size_x);
im_skel(1,1:32)=1;


im_dist = bwdist(im_skel,'Euclidean');
[Gmag,Gdir] = imgradient(im_dist);

[imx,imy,imz,im_weight]=s3_recon_profile_2(0,helicity,domain,domainWall,im_dist,Gdir);
plot_rgb_vec(imx,imy,imz)

magx = imx;
magy = imy;
magz = imz;

ovf_filename='simpleDW_CCWblochwall_30nm.ovf';
mag_mat=zeros([sim_size*sim_size*sim_height,3]);

act_mat=[reshape(rot90(fliplr(magx)),sim_size*sim_size,1),reshape(rot90(fliplr(magy)),sim_size*sim_size,1),reshape(rot90(fliplr(magz)),sim_size*sim_size,1)];
act_mat_l=sim_size*sim_size;
for coli=0:2%0:3:28
    mag_mat((coli)*act_mat_l+1:((coli)*act_mat_l+act_mat_l),:)=act_mat;
end

%dlmwrite('mag_mat.txt',mag_mat,' ')

ovfhead=["#"    "OOMMF:"               "rectangular"               "mesh"    "v1.0"    ""...
    "#"    "Segment"              "count:"                    "1"       ""        "" ...
    "#"    "Begin:"               "Segment"                   ""        ""        "" ...
    "#"    "Begin:"               "Header"                    ""        ""        "" ...
    "#"    "Desc:"                "Time"                      "(s)"     ":"       "0"...
    "#"    "Title:"               "m"                         ""        ""        "" ...
    "#"    "meshtype:"            "rectangular"               ""        ""        "" ...
    "#"    "meshunit:"            "m"                         ""        ""        "" ...
    "#"    "xbase:"               "4e-09"                     ""        ""        "" ...
    "#"    "ybase:"               "4e-09"                     ""        ""        "" ...
    "#"    "zbase:"               "5e-10"                     ""        ""        "" ...
    "#"    "xstepsize:"           "1e-09"                     ""        ""        "" ...
    "#"    "ystepsize:"           "1e-09"                     ""        ""        "" ...
    "#"    "zstepsize:"           "1e-09"                     ""        ""        "" ...
    "#"    "xmin:"                "0"                         ""        ""        "" ...
    "#"    "ymin:"                "0"                         ""        ""        "" ...
    "#"    "zmin:"                "0"                         ""        ""        "" ...
    "#"    "xmax:"                "0.128e-06"                 ""        ""        "" ...
    "#"    "ymax:"                "1.128e-06"                 ""        ""        "" ...
    "#"    "zmax:"                "1.0000000000000000e-07"    ""        ""        "" ...
    "#"    "xnodes:"              "32"                       ""        ""        "" ...
    "#"    "ynodes:"              "512"                       ""        ""        "" ...
    "#"    "znodes:"              "100"                       ""        ""        "" ...
    "#"    "ValueRangeMinMag:"    "1e-08"                     ""        ""        "" ...
    "#"    "ValueRangeMaxMag:"    "1"                         ""        ""        "" ...
    "#"    "valueunit:"           ""                          ""        ""        "" ...
    "#"    "valuemultiplier:"     "1"                         ""        ""        "" ...
    "#"    "End:"                 "Header"                    ""        ""        "" ...
    "#"    "Begin:"               "Data"                      "Text"    ""        "" ];

ovftail=["#" "End:" "Data Text"...
"#" "End:" "Segment"];

fileID = fopen(ovf_filename,'w+');
fprintf(fileID,'%s %s %s %s %s%s\n',ovfhead);
fprintf(fileID,'%.2f %.2f %.2f\n',mag_mat');
fprintf(fileID,'%s %s %s \n%s %s %s\n',ovftail);
fclose('all')