function []=m2_convet2mumax(ovf_filename,xy_size,z_size,effz_size,imxBi,imyBi,imzBi,altx,alty,altz)
%ovf_filename='stripe_p400nm_w200nm_updown.ovf';
%altxyz:0 if same for all layers  :1 if alternates between layers

%xy_size=256; %in cells
%z_size=128; %in cells
mag_mat=zeros([xy_size*xy_size*z_size,3]);

[mn,mm]=size(imzBi);
magx=imxBi;%(floor(mn/2-getl/2):floor(mn/2+getl/2),floor(mm/2-getl/2):floor(mm/2+getl/2));
magy=imyBi;%(floor(mn/2-getl/2):floor(mn/2+getl/2),floor(mm/2-getl/2):floor(mm/2+getl/2));
magz=imzBi;%(floor(mn/2-getl/2):floor(mn/2+getl/2),floor(mm/2-getl/2):floor(mm/2+getl/2));

altx=-2*(altx-0.5);
alty=-2*(alty-0.5);
altz=-2*(altz-0.5);

magx = imresize(magx,[xy_size,xy_size]);
magy = imresize(magy,[xy_size,xy_size]);
magz = imresize(magz,[xy_size,xy_size]);

act_mat1=[reshape(rot90(fliplr(magx)),xy_size*xy_size,1),reshape(rot90(fliplr(magy)),xy_size*xy_size,1),reshape(rot90(fliplr(magz)),xy_size*xy_size,1)];
act_mat2=[reshape(rot90(fliplr(altx*magx)),xy_size*xy_size,1),reshape(rot90(fliplr(alty*magy)),xy_size*xy_size,1),reshape(rot90(fliplr(altz*magz)),xy_size*xy_size,1)];

act_mat_l=xy_size*xy_size;
%effz_size=13;
for coli=0:2:effz_size-1
    mag_mat((coli)*act_mat_l+1:((coli)*act_mat_l+act_mat_l),:)=act_mat1;
end
for coli=1:2:effz_size-1
    mag_mat((coli)*act_mat_l+1:((coli)*act_mat_l+act_mat_l),:)=act_mat2;
end

%dlmwrite('mag_mat.txt',mag_mat,' ')

ovfhead=["#"    "OOMMF:"               "rectangular"               "mesh"    "v1.0"    ""...
    "#"    "Segment"              "count:"                    "1"       ""        "" ...
    "#"    "Begin:"               "Segment"                   ""        ""        "" ...
    "#"    "Begin:"               "Header"                    ""        ""        "" ...
    "#"    "Desc:"                "Time"                      "(s)"     ":"       "0"...
    "#"    "Title:"               "m"                         ""        ""        "" ...
    "#"    "meshtype:"            "rectangular"               ""        ""        "" ...
    "#"    "meshunit:"            "m"                         ""        ""        "" ...
    "#"    "xbase:"               "10e-06"                    ""        ""        "" ...
    "#"    "ybase:"               "10e-06"                    ""        ""        "" ...
    "#"    "zbase:"               "384e-09"                   ""        ""        "" ...
    "#"    "xstepsize:"           "39.0625e-09"               ""        ""        "" ...
    "#"    "ystepsize:"           "39.0625e-09"               ""        ""        "" ...
    "#"    "zstepsize:"           "3e-09"                     ""        ""        "" ...
    "#"    "xmin:"                "0"                         ""        ""        "" ...
    "#"    "ymin:"                "0"                         ""        ""        "" ...
    "#"    "zmin:"                "0"                         ""        ""        "" ...
    "#"    "xmax:"                "10.00e-06"                 ""        ""        "" ...
    "#"    "ymax:"                "10.00e-06"                 ""        ""        "" ...
    "#"    "zmax:"                "384.00e-0"                 ""        ""        "" ...
    "#"    "xnodes:"              "256"                       ""        ""        "" ...
    "#"    "ynodes:"              "256"                       ""        ""        "" ...
    "#"    "znodes:"              "128"                       ""        ""        "" ...
    "#"    "ValueRangeMinMag:"    "1e-08"                     ""        ""        "" ...
    "#"    "ValueRangeMaxMag:"    "1"                         ""        ""        "" ...
    "#"    "valueunit:"           ""                          ""        ""        "" ...
    "#"    "valuemultiplier:"     "1"                         ""        ""        "" ...
    "#"    "End:"                 "Header"                    ""        ""        "" ...
    "#"    "Begin:"               "Data"                      "Text"    ""        "" ];

ovftail=["#" "End:" "Data Text"...
"#" "End:" "Segment"];

fileID = fopen(ovf_filename,'w+');
fprintf(fileID,'%s %s %s %s %s%s\n',ovfhead);
fprintf(fileID,'%.2f %.2f %.2f\n',mag_mat');
fprintf(fileID,'%s %s %s \n%s %s %s\n',ovftail);
fclose('all')
end